"use client";
import { FormEvent,useEffect,useState } from "react";
type Settings={senderName:string;senderEmail:string;companyName:string;offer:string;audience:string;proof:string;retentionDays:number};
type Prospect={id:string;name:string;role:string;company:string;researchCount:number;lastResearchedAt:string};
export function WorkspaceTools(){const[open,setOpen]=useState(false);const[tab,setTab]=useState<"settings"|"history"|"bulk"|"team">("settings");const[settings,setSettings]=useState<Settings>({senderName:"",senderEmail:"",companyName:"",offer:"",audience:"",proof:"",retentionDays:90});const[history,setHistory]=useState<Prospect[]>([]);const[message,setMessage]=useState("");
async function load(){const[a,b]=await Promise.all([fetch("/api/settings"),fetch("/api/history")]);if(a.ok)setSettings(await a.json());if(b.ok)setHistory((await b.json()).prospects);}useEffect(()=>{void (async()=>{await load()})()},[]);
async function save(event:FormEvent){event.preventDefault();const r=await fetch("/api/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});setMessage(r.ok?"Settings saved.":(await r.json()).error);}
async function bulk(event:FormEvent<HTMLFormElement>){event.preventDefault();const csv=String(new FormData(event.currentTarget).get("csv"));const r=await fetch("/api/bulk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({csv})});const d=await r.json();setMessage(r.ok?`${d.created} created, ${d.duplicates} duplicates, ${d.invalid} invalid.`:d.error);if(r.ok)load();}
async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const r=await fetch("/api/team",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:f.get("email"),role:f.get("role")})});const d=await r.json();setMessage(r.ok?`Invite created. Share this token securely: ${d.inviteToken}`:d.error);}
return <><button className="tools-toggle" onClick={()=>setOpen(!open)}>{open?"Close workspace":"Workspace tools"}</button>{open&&<section className="tools-panel shell"><div className="tool-tabs">{(["settings","history","bulk","team"] as const).map(x=><button className={tab===x?"active":""} key={x} onClick={()=>{setTab(x);setMessage("")}}>{x}</button>)}</div>{message&&<p className="notice">{message}</p>}
{tab==="settings"&&<form className="settings-grid" onSubmit={save}><label>Sender name<input value={settings.senderName} onChange={e=>setSettings({...settings,senderName:e.target.value})}/></label><label>Verified sender email<input type="email" value={settings.senderEmail} onChange={e=>setSettings({...settings,senderEmail:e.target.value})}/></label><label>Company name<input value={settings.companyName} onChange={e=>setSettings({...settings,companyName:e.target.value})}/></label><label>Ideal audience<input value={settings.audience} onChange={e=>setSettings({...settings,audience:e.target.value})}/></label><label className="wide">Offer<textarea value={settings.offer} onChange={e=>setSettings({...settings,offer:e.target.value})}/></label><label className="wide">Proof points<textarea value={settings.proof} onChange={e=>setSettings({...settings,proof:e.target.value})}/></label><label>Retention days<input type="number" min="1" max="3650" value={settings.retentionDays} onChange={e=>setSettings({...settings,retentionDays:Number(e.target.value)})}/></label><button>Save settings</button></form>}
{tab==="history"&&<div className="history-list">{history.length?history.map(p=><div key={p.id}><b>{p.name}</b><span>{p.role} · {p.company}</span><small>{p.researchCount} research run(s)</small></div>):<p>No prospects yet.</p>}</div>}
{tab==="bulk"&&<form onSubmit={bulk} className="bulk-form"><p>Paste CSV with a <code>linkedin_url</code> column. Optional: name, role, company, location.</p><textarea name="csv" required placeholder={'linkedin_url,name,role,company\nhttps://linkedin.com/in/example,Example Person,VP Sales,Acme'}/><button>Import prospects</button></form>}
{tab==="team"&&<form onSubmit={invite} className="invite-form"><label>Teammate email<input name="email" type="email" required/></label><label>Role<select name="role"><option value="member">Member</option><option value="admin">Admin</option></select></label><button>Create invitation</button></form>}</section>}</>}
