"use client";
import Image from "next/image";
import {FormEvent,useState} from "react";

export default function Login(){
  const[mode,setMode]=useState<"login"|"register">("login");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[showPassword,setShowPassword]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const body=Object.fromEntries(form);const response=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error||"Unable to continue.");return;}window.location.href="/";}
  return <main className="auth-page"><section className="auth-card"><a className="brand brand-logo auth-logo" href="/login"><Image src="/brand/asp-logo.png" alt="Autonomous Sales Prospector" width={842} height={410} priority/></a><div className="eyebrow">{mode==="login"?"Welcome back":"Create your workspace"}</div><h1>{mode==="login"?"Sign in":"Start prospecting responsibly"}</h1><form onSubmit={submit}>{mode==="register"&&<><label htmlFor="name">Your name</label><input id="name" name="name" required/><label htmlFor="workspaceName">Workspace name</label><input id="workspaceName" name="workspaceName" required/></>}<label htmlFor="email">Email</label><input id="email" name="email" type="email" required/><label htmlFor="password">Password</label><div className="password-field"><input id="password" name="password" type={showPassword?"text":"password"} minLength={10} required/><button type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?"Hide":"Show"}</button></div>{error&&<p className="error-message">{error}</p>}<button disabled={busy}>{busy?"Please wait...":mode==="login"?"Sign in":"Create account"}</button></form><button className="text-button" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Need an account? Create one":"Already have an account? Sign in"}</button><div className="auth-meta"><a href="/how-it-works">How it works</a><a href="/support">Support</a><span>v1.0.0 · HSK-Group</span></div></section></main>;
}
