"use client";
import Image from "next/image";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
type Issue={id:string;category:string;subject:string;severity:string;status:string;appVersion:string;createdAt:string};
export default function Support(){
  const[issues,setIssues]=useState<Issue[]>([]),[message,setMessage]=useState("");
  async function load(){const r=await fetch("/api/support/issues");if(r.status===401){location.href="/login";return}const b=await r.json();setIssues(b.issues||[])}
  useEffect(()=>{fetch("/api/support/issues").then(r=>{if(r.status===401){location.href="/login";return null}return r.json()}).then(b=>{if(b)setIssues(b.issues||[])})},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const payload={...Object.fromEntries(new FormData(form)),pageUrl:location.href};const r=await fetch("/api/support/issues",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){setMessage(b.error||"Unable to submit.");return}form.reset();setMessage(`Ticket ${b.id} recorded.`);await load()}
  return <main className="info-page"><Link className="product-logo" href="/"><Image src="/brand/asp-logo.png" alt="Autonomous Sales Prospector" width={842} height={410} priority/></Link><section className="info-card"><span className="eyebrow">SUPPORT</span><h1>Complaints, issues and feedback</h1><p>Tickets are stored in your workspace with the application version and audit context.</p><form className="support-form" onSubmit={submit}><label>Category<select name="category"><option value="issue">Technical issue</option><option value="complaint">Complaint</option><option value="feedback">Feedback</option><option value="privacy">Privacy</option><option value="billing">Billing</option></select></label><label>Severity<select name="severity"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className="wide">Subject<input name="subject" minLength={3} required/></label><label className="wide">Description<textarea name="description" minLength={10} rows={7} required/></label><button>Submit ticket</button></form>{message&&<p className="notice">{message}</p>}<h2>Workspace tickets</h2>{issues.length?issues.map(i=><div className="issue-row" key={i.id}><b>{i.subject}</b><span>{i.category} · {i.severity} · {i.status} · v{i.appVersion}</span></div>):<p>No tickets yet.</p>}</section></main>;
}
